spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5433/postgres
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: validate
      naming.physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties.hibernate:
      show_sql: true
      format_sql: true
    open-in-view: false
  data:
    web.pageable.default-page-size: 20

logging.file.path: src/main/resources/log

server:
  port: 8080
  servlet:
    context-path: /api
